version: "2"
services:
    web:
        image: docker.io/samir27110/samke-frontend
        ports:
            - 80:80
    api:
        image: docker.io/samir27110/samke-backend
        depends_on:
            - web
        ports:
            - 5000:80

